apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-one
spec:
  selector:
    matchLabels:
      system: ReplicaOne
  template:
    metadata:
      name: rs-one
      labels:
        system: DaemonSet
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1
        ports:
          - containerPort: 80